name: Code Quality Checks

on:
  commit:
    branches: [develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Check for syntax errors
        run: npx eslint .

      - name: Check formatting
        run: npx prettier --check .

      - name: Check SCSS variable usage
        run: npx stylelint "**/*.scss" --syntax scss --custom-syntax node_modules/@elsewhencode/scss-syntax/scss-syntax.js --rules "plugin/scss-vars-checker"

      - name: Check for empty SCSS classes
        run: npx sass-lint -v --no-exit --max-warnings 0 --format stylish '**/*.scss'

      - name: Check for color tags instead of constants
        run: npx sass-lint -v --no-exit --max-warnings 0 --format stylish '**/*.scss' --rule 'color-hex-length: always-where-possible'
